"""add_conversations_and_messages_tables

Revision ID: 37eb9289ad1b
Revises: 3ff5a85a4ac0
Create Date: 2026-04-01 16:16:47.574398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37eb9289ad1b'
down_revision: Union[str, Sequence[str], None] = '3ff5a85a4ac0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Explicitly create the ENUM type in PostgreSQL before altering the column
    messagetype = sa.Enum('TEXT', 'IMAGE', 'AUDIO', name='messagetype')
    messagetype.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('media_url', sa.String(length=250), nullable=True))
    op.add_column('messages', sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False))
    op.add_column('messages', sa.Column('text', sa.Text(), nullable=True))
    op.alter_column('messages', 'message_type',
               existing_type=sa.VARCHAR(length=50),
               type_=messagetype,
               postgresql_using='message_type::messagetype',
               existing_nullable=False)
    op.drop_column('messages', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.alter_column('messages', 'message_type',
               existing_type=sa.Enum('TEXT', 'IMAGE', 'AUDIO', name='messagetype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('messages', 'text')
    op.drop_column('messages', 'timestamp')
    op.drop_column('messages', 'media_url')
    # ### end Alembic commands ###
    
    # Clean up the ENUM type when downgrading
    messagetype = sa.Enum('TEXT', 'IMAGE', 'AUDIO', name='messagetype')
    messagetype.drop(op.get_bind(), checkfirst=True)
