"""remove rag_container_id

Revision ID: 89ca65fd51c2
Revises: 591053742c1a
Create Date: 2026-04-10 01:33:49.888359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89ca65fd51c2'
down_revision: Union[str, Sequence[str], None] = '591053742c1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_bucket_registry_rag_container_id'), table_name='knowledge_bucket_registry')
    op.drop_column('knowledge_bucket_registry', 'rag_container_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_bucket_registry', sa.Column('rag_container_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_knowledge_bucket_registry_rag_container_id'), 'knowledge_bucket_registry', ['rag_container_id'], unique=False)
    # ### end Alembic commands ###
