"""add_first_and_last_name_to_users

Revision ID: b078d41f341d
Revises: c9580148da86
Create Date: 2026-04-01 23:26:50.646876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b078d41f341d'
down_revision: Union[str, Sequence[str], None] = 'c9580148da86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=100), server_default='', nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
