"""add_channel_identifiers_to_agents

Revision ID: c9580148da86
Revises: dd4a7ad3dedb
Create Date: 2026-04-01 20:47:44.717178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9580148da86'
down_revision: Union[str, Sequence[str], None] = 'dd4a7ad3dedb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('whatsapp_number', sa.String(length=50), nullable=True))
    op.add_column('agents', sa.Column('telegram_bot_username', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_agents_telegram_bot_username'), 'agents', ['telegram_bot_username'], unique=False)
    op.create_index(op.f('ix_agents_whatsapp_number'), 'agents', ['whatsapp_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agents_whatsapp_number'), table_name='agents')
    op.drop_index(op.f('ix_agents_telegram_bot_username'), table_name='agents')
    op.drop_column('agents', 'telegram_bot_username')
    op.drop_column('agents', 'whatsapp_number')
    # ### end Alembic commands ###
